---
- hosts: localhost
  tasks:
    - name: Create user artifactory-docker with home dir under /home/artifactory-docker
      user:
        name: artifactory-docker
        system: yes
        createhome: yes
        home: /home/artifactory-docker
        state: present
        uid: 104
        shell: /bin/false
    - name: Creates directory to mount artifactory data
      file:
        path: /home/artifactory-docker/DATA
        state: directory
        owner: artifactory-docker
        group: 107
    - name: Creates artifactory sub-dir
      file:
        path: /home/artifactory-docker/DATA/artifactory
        state: directory
        owner: artifactory-docker
        group: 107
    - name: Creates artifactory etc dir
      file:
        path: /home/artifactory-docker/DATA/artifactory/etc
        state: directory
        owner: artifactory-docker
        group: 107
    - name: Creates artifactory nginx dir
      file:
        path: /home/artifactory-docker/DATA/nginx
        state: directory
        owner: artifactory-docker
        group: 107
    - name: Creates artifactory nginx/conf.d dir
      file:
        path: /home/artifactory-docker/DATA/nginx/conf.d
        state: directory
        owner: artifactory-docker
        group: 107
    - name: Creates artifactory nginx/log dir
      file:
        path: /home/artifactory-docker/DATA/nginx/log
        state: directory
        owner: artifactory-docker
        group: 107
    - name: Creates artifactory nginx/ssl dir
      file:
        path: /home/artifactory-docker/DATA/nginx/ssl
        state: directory
        owner: artifactory-docker
        group: 107
#    - name: Install communication-key file
#      copy:
#        src: ../files/artifactory/security/communication.key
#        dest: /home/artifactory-docker/DATA/artifactory/etc
#        owner: artifactory-docker
#
#    - name: Install access keys
#      copy:
#        src: ../files/artifactory/access
#        dest: /home/artifactory-docker/DATA/artifactory/etc
#        owner: artifactory-docker
    - name: Nginx Proxy Configuration
      copy:
        src: ../files/artifactory/nginx/conf.d/
        dest: /home/artifactory-docker/DATA/nginx/conf.d
        owner: artifactory-docker
        group: 107
        force: no
    - name: Creates artifactory addon-drivers
      file:
        path: /home/artifactory-docker/DATA/addon-drivers
        state: directory
        owner: artifactory-docker
        group: 107
    - name: Add Oracle JDBC Driver 12.1.0.1
      copy:
       src: ../files/artifactory/ojdbc7-12.1.0.1.jar
       dest: /home/artifactory-docker/DATA/addon-drivers/ojdbc7.jar
       owner: artifactory-docker
       group: 107
