---
- hosts: localhost
  tasks:
    - name: Install Docker CE
      zypper:
        name: docker
        state: present
    - name: Install docker-compose
      zypper:
        name: docker-compose
        state: present
    - name: Start Docker on boot
      service:
        name: docker
        enabled: yes
    - name: Start Docker now if its not running
      service:
        name: docker
        state: started
