---
- hosts: localhost
  tasks:
    - name: Install Docker CE
      zypper:
        name: docker
        state: present
    - name: UnInstall SLES docker-compose because its broken
      zypper:
        name: docker-compose
        state: absent
    - name: Start Docker on boot
      service:
        name: docker
        enabled: yes
    - name: Start Docker now if its not running
      service:
        name: docker
        state: started
    - name: Install static compiled docker-compose
      copy:
        src: ../../tools/docker-compose
        dest: /usr/local/bin/docker-compose
        backup: no
        owner: root
        group: root
        mode: u=rwx,g=rwx,o=rx


