---
- hosts: localhost
  tasks:
    - name: Install Docker CE
      zypper:
        name: docker
        state: present
    - name: Install docker-compose
      zypper:
        name: docker-compose
        state: present
    - name: Start Docker on boot
      service:
        name: docker
        enabled: yes
    - name: Start Docker now if its not running
      service:
        name: docker
        state: started
    - name: Install python-pip
      zypper:
        name: python-pip
        state: present
    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present
        version: 1.15.0
    - name: Install docker-py
      pip:
        name: docker-py
        state: present

