---
- hosts: localhost
  tasks:
    - name: Create user jenkins-docker
      user:
        name: jenkins-docker
        createhome: no
        shell: /bin/false
        system: yes
        state: present
