version: '2'
services:
  nginx:
    image: nginx:1.12.1-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d
    restart: always

  dockergen:
    image: jwilder/docker-gen:0.7.3
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    restart: always

  clearingunit:
    image: rewe/clearing-unit
    environment:
      - VIRTUAL_HOST=docker.local
      - VIRTUAL_PORT=8080
    depends_on:
      - nginx
    restart: always
    user: "61001"
