version: '2'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:5.5.2
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - /home/artifactory-docker/DATA/artifactory:/var/opt/jfrog/artifactory
     - /home/artifactory-docker/DATA/addon-drivers/ojdbc7.jar:/opt/jfrog/artifactory/tomcat/lib/ojdbc7.jar
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
        
  nginx:
    image: docker.bintray.io/jfrog/nginx-artifactory-pro:5.5.2
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
     - artifactory
    links:
     - artifactory
    volumes:
     - /home/artifactory-docker/DATA/nginx:/var/opt/jfrog/nginx
    environment:
     - ART_BASE_URL=http://artifactory:8081/artifactory
     - SSL=true
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
