version: '2'
services:
  dind-17-04-0-ce:
    image: docker:17.04.0-ce-dind
    container_name: dind-17-04-0-ce
    ports:
      - "17040:2375"
    privileged: true
    restart: always
    volumes:
      - /home/dind/DATA/dind-17.04.0:/var/lib/docker
