version: '2'
services:
  nginx:
    image: nginx:1.12.1-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d
    restart: always

  dockergen:
    image: jwilder/docker-gen:0.7.3
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    restart: always

  bitbucket:
    image: atlassian/bitbucket-server:5.5
    environment:
      - VIRTUAL_HOST=docker.local
      - VIRTUAL_PORT=7990
      - JAVA_OPTS=-server -Xms2g -Xmx8g -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1
    ports:
      - "7999:7999"
    volumes:
      - /home/bitbucket-docker/DATA/bitbucket:/var/atlassian/application-data/bitbucket
    depends_on:
      - nginx
    restart: always
    user: "60002"
volumes:
  bitbucket_home: